version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev 
        ports:
            - "3001:3000"
        volumes:
            - /usr/app/fe/node_modules
            - .:/usr/app/fe
    # tests:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.dev 
    #     volumes:
    #             - /usr/app/fe/node_modules
    #             - .:/usr/app/fe
    #     command: ["npm", "run", "test"]